name: troubleshooter
description: "A Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  stacked: ^3.4.2
  go_router: ^5.2.0
  url_launcher: ^6.2.6
  get: ^4.6.6
  shared_preferences: ^2.2.3
  share_plus: ^4.1.0
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  firebase_core: ^2.31.0
  firebase_analytics: ^10.10.5
  flutter_dotenv: ^5.1.0
  audioplayers: ^6.0.0
  flutter_sensors: ^1.0.1
  flutter_svg: ^2.0.10+1
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/headericon.png
    - lib/assets/mainscreensDm.png
    - lib/assets/mainscreensLm.png
    - lib/assets/images/index0.png
    - lib/assets/images/index1.png
    - lib/assets/images/index4.png
    - lib/assets/images/index7.png
    - lib/assets/select.png
    - audio/sound_spin.mp3
    - lib/assets/s1.svg
    - lib/assets/sound-on.svg
    - lib/assets/sound-off.svg
    - lib/assets/vibrate.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-Thin.ttf
    - family: Madimi
      fonts:
        - asset: fonts/Madimi/Madimi-Regular.ttf
