// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNGg2k_Wjaftgv5vyfgqxEVHrg5m_x2fw',
    appId: '1:491790797855:web:d6d4e79f508d97a51cd92a',
    messagingSenderId: '491790797855',
    projectId: 'haiderwebanalytics',
    authDomain: 'haiderwebanalytics.firebaseapp.com',
    storageBucket: 'haiderwebanalytics.appspot.com',
    measurementId: 'G-H6Y7R26TT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77-dhRsNtTc-B2PYE_9tuLOAryoRVEro',
    appId: '1:491790797855:android:4135f37b7d39ed6a1cd92a',
    messagingSenderId: '491790797855',
    projectId: 'haiderwebanalytics',
    storageBucket: 'haiderwebanalytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDftkHBHpwnieEJtGqMOaLbgn5i7FO9jlI',
    appId: '1:491790797855:ios:b40f4edf7b8c14251cd92a',
    messagingSenderId: '491790797855',
    projectId: 'haiderwebanalytics',
    storageBucket: 'haiderwebanalytics.appspot.com',
    iosBundleId: 'com.example.troubleshooter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDftkHBHpwnieEJtGqMOaLbgn5i7FO9jlI',
    appId: '1:491790797855:ios:b40f4edf7b8c14251cd92a',
    messagingSenderId: '491790797855',
    projectId: 'haiderwebanalytics',
    storageBucket: 'haiderwebanalytics.appspot.com',
    iosBundleId: 'com.example.troubleshooter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNGg2k_Wjaftgv5vyfgqxEVHrg5m_x2fw',
    appId: '1:491790797855:web:7aaa00ff4d604d571cd92a',
    messagingSenderId: '491790797855',
    projectId: 'haiderwebanalytics',
    authDomain: 'haiderwebanalytics.firebaseapp.com',
    storageBucket: 'haiderwebanalytics.appspot.com',
    measurementId: 'G-ZFQMFSKXT3',
  );
}
